Models/DatabaseManagement.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseManager.Models
{
    public static class DatabaseManagement
    { 
        public static List<Report> Reports = new List<Report>();
        
        public static Report SelectedReport = new();

        
        public static void AddReportToDb(Report report)
        {
            using (Context context = new Context())
            {
                report.Id = context.Reports.Count();
                context.Reports.Add(report);
                context.SaveChanges();
            }
        }

        public static void DeleteReportFromDb(Report report)
        {
            using (Context context = new Context())
            {
                Report reportToRemove = context.Reports.First(p => p.Id == report.Id);
                context.Reports.Remove(reportToRemove);
                context.Entry(reportToRemove).State = EntityState.Deleted;
                context.SaveChanges();
            }
        }

        public static void MarkReportComplete(Report report)
        {
            using (Context context = new Context())
            {
                Report reportToEdit = context.Reports.First(p => p.Id == report.Id);
                reportToEdit.MarkComplete();
                context.Entry(reportToEdit).State = EntityState.Modified;
                context.SaveChanges();
            }
        }
    }
}

Models/ErrorViewModel.cs
namespace DatabaseManager.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Report.cs
using System;
using System.Drawing;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseManager.Models
{
    public class Report
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Coordinates { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string TimeOfReport { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; } = false;

        public Report() 
        {
            Address = "";
            Coordinates = "";
            Email = "";
            PhoneNumber = "";
            TimeOfReport = DateTime.Now.ToString();
            Description = "";
            Completed = false;
        }
    
        public string DisplayAddress()
        {
            return "Location: " + Address;
        }

        public string DisplayCoords()
        {
            string[] coords = Coordinates.Split(",");
            return coords[0] + ", " + coords[1];
        }

        public string DisplayContactInfo()
        {
            string contactInfo = "";
            if(Email != "")
            {
                contactInfo += Email;
            }

            if(Email != "" && PhoneNumber != "")
            {
                contactInfo += ", ";
            }

            if(PhoneNumber != "")
            {
                contactInfo += PhoneNumber;
            }

            return contactInfo;
        }

        public bool HasContactInfo()
        {
            return Email != "" || PhoneNumber != "";
        }
        public string DisplayReportTime()
        {
            return "Report Time: " + TimeOfReport;
        }
        public string DisplayTime()
        {
            return "Coordinates: " + Coordinates;
        }
        public string DisplayDescription()
        {
            return Description;
        }

        public void DeletePersonalInfo()
        {
            Email = "";
            PhoneNumber = "";
        }

        public void MarkComplete()
        {
            Completed = true;
            //Send completed message to reportee if left contact info
            DeletePersonalInfo();
        }
    }
}

Controllers/DatabaseManagerController.cs
using DatabaseManager;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Web.Helpers;

namespace DatabaseManager.Controllers
{
    public class DatabaseManagerController : Controller
    {
        private readonly ILogger<DatabaseManagerController> _logger;
        public static Report reportToDelete = new Report();
        public DatabaseManagerController(ILogger<DatabaseManagerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Report Flytipping In Your Area";
            return RedirectToAction("Dashboard");
        }

        public IActionResult Report()
        {
            ViewBag.Title = "Report Flytipping In Your Area";
            return View();
        }

        public IActionResult Dashboard()
        {
            ViewBag.Title = "Flytipping Dashboard";
            return View();
        }

        [ActionName("Report"), HttpPost]
        public IActionResult Report(string address, string description, string email, string phoneNumber, string coords)
        {
            
            Report reportToAdd = new Report()
            {
                Address = ModelState["Address"].AttemptedValue,
                Coordinates = ModelState["Coords"].AttemptedValue,
                PhoneNumber = ModelState["PhoneNumber"].AttemptedValue,
                Email = ModelState["Email"].AttemptedValue,
                TimeOfReport = DateTime.Now.ToString(),
                Description = ModelState["Description"].AttemptedValue
            };
            DatabaseManagement.AddReportToDb(reportToAdd);
            
            return RedirectToAction("Dashboard");
        }

        public IActionResult ReportDelete()
        {
            ViewBag.Title = "Delete Report";
            return View();
        }

        public ActionResult DeleteReport(string deleteReport)
        {
            using (Context context = new Context())
            {
                DatabaseManagement.SelectedReport = context.Reports.Find(Int32.Parse(deleteReport));
            }
            return RedirectToAction("ReportDelete");

        }

        public ActionResult ConfirmDelete()
        {
            using (Context context = new Context())
            {
                DatabaseManagement.DeleteReportFromDb(DatabaseManagement.SelectedReport);
            }
            return RedirectToAction("Dashboard");
        }
        public IActionResult ReportComplete()
        {
            ViewBag.Title = "Complete Report";
            return View();
        }

        public ActionResult MarkReportCompleted(string completeReport)
        {
            using (Context context = new Context())
            {
                DatabaseManagement.SelectedReport = context.Reports.Find(Int32.Parse(completeReport));
            }
            return RedirectToAction("ReportComplete");
        }

        public ActionResult ConfirmComplete()
        {
            using (Context context = new Context())
            {
                DatabaseManagement.MarkReportComplete(DatabaseManagement.SelectedReport);
            }
            return RedirectToAction("Dashboard");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/DatabaseManager/Dashboard.cshtml
<nav class="main-nav-btns row-flex flex-center">
    <a href="/DatabaseManager/Report" class="btn">Add Entry</a>
</nav>

<main class=" search-results-cntr column-flex">

@using(Context context = new Context())
{
    if( context.Reports.Count() == 0) { 
        <p class="text-center">The report database is empty.</p>
    } 
    else
    {
        @foreach (Report report in context.Reports)
        {
            <div class="search-result row-flex flex-between">
                <aside class="search-result-btn-cntr">
                    @using (Html.BeginForm("DeleteReport", "DatabaseManager"))
                    {
                        <button class="btn delete-btn" name="deleteReport" type="submit" value="@report.Id">Delete</button>
                    }
                    @if (!report.Completed)
                    {
                        @using (Html.BeginForm("MarkReportCompleted", "DatabaseManager"))
                        {
                            <button class="btn complete-btn" name="completeReport" type="submit" value="@report.Id">Mark Complete</button>
                        }

                    }
                </aside>

                
               
                <section class="result-detail">
                    <h4 class="detail-element">ID: @report.Id</h4>
                    @if(report.Address != "")
                    {
                        <p class="detail-element">Address: @report.Address</p>
                    }
                        

                    <p class="detail-element">Date of Report: @report.TimeOfReport.Split(" ")[0]</p>

                    <p class="detail-element">Time of Report: @report.TimeOfReport.Split(" ")[1]</p>

                    <p class="detail-element">Description: @report.Description</p>

                    @if (report.Coordinates != null && report.Coordinates != "")
                    {
                        <p class="detail-element">@report.DisplayCoords()</p>
                    }

                    @if (report.HasContactInfo())
                    {
                        <p class="detail-element">Reportee contact info: @report.DisplayContactInfo()</p>
                    }

                    @if (report.Completed)
                    {
                        <p class="detail-element">Report Completed</p>
                    }
                    else
                    {
                        <p class="detail-element">Report Incomplete</p>
                    }
                </section>
                
            </div>
        }
    }
}
</main>

Views/DatabaseManager/Index.cshtml
<main class="main-nav-btns flex-center">
    <a class="btn" href="/DatabaseManager/Report">Report</a>
    <a class="btn" href="/DatabaseManager/Dashboard">Dashboard</a>
</main>

Views/DatabaseManager/Report.cshtml
<main id="report-add" class="container">
    <h3 class="text-center">Report a Flytipping incident</h3>

    <form class="column-flex form" method="post" enctype="multipart/form-data">
        <label for="reportAddressInput">Report Address:</label>
        <input id="reportAddressInput" name="address">
        <p>Either a text address OR a map pin location is required, you do not have to do both.</p>

        <label for="reportCoordinatesInput">Map Pin location Input:</label>
        <div id="map">
            <input id="reportCoordinatesInput" name="coords">
        </div>

        <label for="reportDescriptionInput">Description:*</label>
        <input id="reportDescriptionInput" name="description">
        <p>Please leave any addition information about the incident that you can</p>

        <label for="emailInput">Email:</label>
        <input id="emailInput" name="email">

        <label for="phoneInput">Phone Number:</label>
        <input id="phoneInput" name="phoneNumber">
        <p>contact information is optional and only needed if you would like to be informed of any updates on the incidents resolution.</p>
        <p>Any contact information submitted to this form will be deleted when the incident has been resolved.</p>
        <p id="reportErrorMessage"></p>
        <button type="submit" id="reportSubmitBtn" class="btn">Submit Report</button>
    
        
    </form>
</main>

<script src="~/js/leafletmap.js" asp-append-version="true"></script>
<script src="~/js/reportValidation.js" asp-append-version="true"></script>

Views/DatabaseManager/ReportComplete.cshtml
<main class="container">
    <h3 class="text-center">Complete Report</h3>

    <div class="search-result row-flex flex-between">
        <article class="flex-cntr column-flex">
            <h4>Report ID: @DatabaseManagement.SelectedReport.Id</h4>

            @if (DatabaseManagement.SelectedReport.Address != "")
            {
                <label>Address:</label>
                <p>@DatabaseManagement.SelectedReport.Address</p>
            }

            @if (DatabaseManagement.SelectedReport.Coordinates != "")
            {
                <label>Coordinates:</label>
                <p>@DatabaseManagement.SelectedReport.DisplayCoords()</p>
            }

            @if (@DatabaseManagement.SelectedReport.HasContactInfo())
            {
                <label>Reportee Contact Info:</label>
                <p>@DatabaseManagement.SelectedReport.DisplayContactInfo()</p>
            }

            <label>Description:</label>
            <p>@DatabaseManagement.SelectedReport.Description</p>

            <label>Date and Time Reported:</label>
            <p>@DatabaseManagement.SelectedReport.TimeOfReport.Split(" ")[1], @DatabaseManagement.SelectedReport.TimeOfReport.Split(" ")[0]</p>
        </article>
        <aside class="search-result-btn-cntr" id="confirm-complete-btn">
            @using (Html.BeginForm("ConfirmComplete", "DatabaseManager"))
            {
                <button class="btn" name="completeReport" type="submit" value="@DatabaseManagement.SelectedReport.Id">Confirm Completion</button>
            }
        </aside>
    </div>
</main>

Views/DatabaseManager/ReportDelete.cshtml
<main class="container">
    <h3 class="text-center">Delete Report</h3>

    <div class="search-result row-flex flex-between">
        <article class="flex-cntr column-flex">
            <h4>Report ID: @DatabaseManagement.SelectedReport.Id</h4>
            
            @if(DatabaseManagement.SelectedReport.Address != "")
            {
                <label>Address:</label>
                <p>@DatabaseManagement.SelectedReport.Address</p>
            }
            
            @if(DatabaseManagement.SelectedReport.Coordinates != "")
            {
                <label>Coordinates:</label>
                <p>@DatabaseManagement.SelectedReport.DisplayCoords()</p>
            }
           
            @if (@DatabaseManagement.SelectedReport.HasContactInfo())
            {
                <label>Reportee Contact Info:</label>
                <p>@DatabaseManagement.SelectedReport.DisplayContactInfo()</p>
            }

            <label>Description:</label>
            <p>@DatabaseManagement.SelectedReport.Description</p>

            <label>Date and Time Reported:</label>
            <p>@DatabaseManagement.SelectedReport.TimeOfReport.Split(" ")[1], @DatabaseManagement.SelectedReport.TimeOfReport.Split(" ")[0]</p>
        </article>
        <aside class="search-result-btn-cntr" id="confirm-delete-btn">
            @using (Html.BeginForm("ConfirmDelete", "DatabaseManager"))
            {
                <button class="btn" name="deleteReport" type="submit" value="@DatabaseManagement.SelectedReport.Id">Confirm Deletion</button>
            }
        </aside>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin="">
    <link rel="shortcut icon" href="~/img/hmm.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <link rel="stylesheet" href="~/DatabaseManager.styles.css" asp-append-version="true">
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> 
             <a class="navbar-brand" asp-controller="DatabaseManager" asp-action="Index">West Northamptonshire Flytipping</a>
        </nav>
    </header>

    @RenderBody()
     
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>